apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: ticketing-microarch
build:
  artifacts:
  - image: manosriram/auth
    context: auth
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yaml
